### ISSUE TITLE
[Feature] Add a custom vertical scrollbar

### ISSUE THREAD

**Issue by KamalDGRT** [Microsoft-Club-SIST/mclub-website#16]
**Is your feature request related to a problem? Please describe.**
I do not find the default scrollbar pleasing to the eyes when compared to the rest of the design.

**Describe the solution you'd like**
An animated scrollbar similar to the one present in [CSS-Tricks](https://css-tricks.com/) Website.

**Comment by Manoj-Paramsetti** [comment]
Created a pull request to fix this issue ( #17 )

**Comment by KamalDGRT** [comment]
Closing this issue as it is fixed by @Manoj-Paramsetti in [#17 ]
