### ISSUE TITLE
[Docs] Add a License file

### ISSUE THREAD

**Issue by dumbbanana** [Microsoft-Club-SIST/mclub-website#5]
**Is your feature request related to a problem? Please describe.**
Usually, open-source projects will have a License file

**Describe the solution you'd like**
Add a suitable License for the repo

**Comment by Manoj-Paramsetti** [comment]
Thanks! @dumbbanana for raising this issue. This issue will be fixed soon!

**Comment by Manoj-Paramsetti** [comment]
This issue is fixed. Thanks for contributing @dumbbanana!
