### ISSUE TITLE
[Feature] Add Events Page

### ISSUE THREAD

**Issue by Manoj-Paramsetti** [Microsoft-Club-SIST/mclub-website#7]
### Things to be added:

- Stylesheet code for events page
- HTML code for events page

Use `/events` branch to work and make a pull request to `/main` while contributing

Page design:
https://imgur.com/KkkpdE1.png

**Comment by nanna7077** [comment]
I'd like to work on this

**Comment by Manoj-Paramsetti** [comment]
This issue is **assigned to you @nanna7077** 
You can start working on this issue ✨
